### PR TITLE
Fix human readable CLI output

### LINKED ISSUE #162: Only return the `result` on human readable CLI
We have unnecessary info right now:
```
{
  "id": "revault-cli-3252059",
  "jsonrpc": "2.0",
  "result": {
    "vaults": [
    ```

### PR DESCRIPTION
**Pull request by danielabrozzoni**
Returning only the content of `result` if success, otherwise returning only `error`

 Fixes #162

### CODE REVIEW

File: src/cli/main.rs [hunk 1]
```diff
@@ -161,7 +161,14 @@ fn main() {
                     if raw {
                         print!("{}", response);
                     } else {
-                        print!("{:#}\n", response);
+                        if let Some(r) = response.get("result") {
+                            // If the response is null, don't print anything
+                            if Json::Null != *r {
+                                println!("{:#}", r);
+                            }
```
Comment (darosior) [inline src/cli/main.rs:168]: Shouldn't we be printing `null` ? Anyways it's a violation of the JSONRPC2 spec to not return an object as result iirc

**Review by darosior — APPROVED** [review]
ACK aaddcf2f86b5c1acc04077c7f47983127d988453

Bikeshedding on the `null`, but meh

File: src/cli/main.rs (hunk 1 above)
Comment (danielabrozzoni) [reply src/cli/main.rs:168]: If you prefer we can return `null`, I'm not really sure what's the convention here

Comment (darosior) [reply src/cli/main.rs:168]: Yeah, let's do that. Don't know what's best either but when in doubt Explicit Is Always Better :tm:

**Comment by darosior** [comment]
ACK 181
