### PR TITLE
Spending process: Cosigning server + Coordinator communication, and Unvault + Spend broadcast

### LINKED ISSUE #118: Fix tests
- [x] Sometimes functional tests remain stuck in CI in `test_reorged_deposit_status`
- [x] Sometimes `test_getspendtx` fails with log [ci.txt](https://github.com/revault/revaultd/files/6155028/ci.txt)
- [x] Sometimes `database::actions::db_sequential_test_runner` fails with:
```
running 4 tests
test jsonrpc::server::tests::test_bytes_reader ... ok
test revaultd::tests::test_from_config ... FAILED
test database::actions::test::db_sequential_test_runner ... ok
test jsonrpc::server::tests::simple_write_recv ... ok

failures:

---- revaultd::tests::test_from_config stdout ----
thread 'revaultd::tests::test_from_config' panicked at 'Creating state from config: WritingKey(Os { code: 17, kind: AlreadyExists, message: "File exists" })', src/daemon/revaultd.rs:540:39
error: test failed, to rerun pass '--bin revaultd'
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### PR DESCRIPTION
**Pull request by darosior**
This implements the spending process on top of #125 .

We add a `spend_transactions` table to the database in order to keep track of PSBTs. A bridge `spend_inputs` table is added as well to join with the Unvault transaction in the `presigned_transactions` table.

This allows to offer to the caller a way to:
1. Create a Spend transaction (previous work, already in master)
2. Store or update a Spend transaction (`updatespendtx`)
3. Delete a stored Spend transaction (`delspendtx`)
4. List the stored Spend transaction along with the vault deposit outpoints they ultimately spend (`listspendtxs`)
5. Trigger the Spending Process by
5.a Checking all managers signed
5.b Requesting the signatures from the cosigning servers
5.c Announcing the Spend transaction to the Coordinator
5.d Broadcasting the Unvault transaction(s)
5.e Later broadcasting the Spend transaction

We also integrate the Cosigning Server in the functional test framework: https://github.com/revault/cosignerd .

This does not contain proper state tracking which will be done in a followup.

Fixes #118

### CODE REVIEW

**Comment by darosior** [comment]
Added a drive-by (hopefully) fix for the second item of #118

**Comment by darosior** [comment]
The last commit was added as a prep work of a more extensive blackbox test of the Spend process, which will finally not happen in this PR. Leaving it though as it's tightly related to the Spend process.

File: .gitmodules [hunk 1]
```diff
@@ -1,3 +1,6 @@
 [submodule "tests/servers/coordinatord"]
 	path = tests/servers/coordinatord
 	url = https://github.com/revault/coordinatord
+[submodule "tests/servers/cosignerd"]
```
Comment (edouardparis) [inline .gitmodules:4]: update tests/README.md https://github.com/revault/revaultd/tree/master/tests#with-the-servers

**Comment by darosior** [comment]
We should not be able to delete a Spend marked as `broadcast = 1`

**Comment by darosior** [comment]
Edouard feedback: `updatespendtx` should not take outpoints

File: .gitmodules (hunk 1 above)
Comment (darosior) [reply .gitmodules:4]: Good catch, thanks!

File: src/daemon/control.rs [hunk 2]
```diff
@@ -1050,6 +1216,208 @@ pub fn handle_rpc_messages(
...
+                    );
+                }
+                // There was an issue with an outpoint, error is already sent in the loop.
+                if db_unvaults.len() != outpoints.len() {
+                    continue;
+                }
+
+                // Does the Spend psbt we are passed actually correspond to the outpoint array?
+                fn all_outpoints_match(
+                    spend_inputs: &Vec<revault_tx::bitcoin::TxIn>,
```
Comment (danielabrozzoni) [inline src/daemon/control.rs:1256]: From `cargo clippy`:
```
warning: writing `&Vec<_>` instead of `&[_]` involves one more reference and cannot be used with non-Vec-based slices.
    --> src/daemon/control.rs:1288:35
     |
1288 |                     spend_inputs: &Vec<revault_tx::bitcoin::TxIn>,
     |                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: change this to: `&[revault_tx::bitcoin::TxIn]`
     |
     = note: `#[warn(clippy::ptr_arg)]` on by default
     = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#ptr_arg
```
(same for `db_unvaults`)

**Comment by darosior** [comment]
- Removed the `outpoints` from `updatespendtx` arguments
- Updated the tests doc
- Added some wannabe-edgecase-testing test cases, new suggestions of not a scenario not currently covered **very welcome**!

File: src/daemon/database/actions.rs [hunk 3]
```diff
@@ -487,7 +487,10 @@ pub fn db_update_presigned_tx(
 /// Insert a new Spend transaction in the database
 pub fn db_insert_spend(
     db_path: &PathBuf,
-    unvault_txs: &[&DbTransaction],
+    // FIXME: Rust newbie: i *don't* need to be moving this. So i want to take &[&T] but i can't
```
Comment (danielabrozzoni) [inline src/daemon/database/actions.rs:490]: You're not moving the transactions, are you?
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=1be844b0305ec94fe385c8efffb5fb74

Comment (darosior) [reply src/daemon/database/actions.rs:490]: Hmm it does move as for example
```patch
diff --git a/src/daemon/database/actions.rs b/src/daemon/database/actions.rs
index 9b370dd..c1e436d 100644
--- a/src/daemon/database/actions.rs
+++ b/src/daemon/database/actions.rs
@@ -1055,7 +1055,7 @@ mod test {
             db_vault_by_unvault_txid(&db_path, &spend_tx_inputs[0].previous_output.txid)
                 .unwrap()
                 .unwrap();
-        db_insert_spend(&db_path, &[db_unvault.clone()], &spend_tx).unwrap();
+        db_insert_spend(&db_path, &[db_unvault], &spend_tx).unwrap();
         let spend_txid = spend_tx.inner_tx().global.unsigned_tx.txid();
         assert_eq!(
             db_list_spends(&db_path).unwrap().get(&spend_txid),
```
Does not compile (with a nice use-after-move error message)

Comment (darosior) [reply src/daemon/database/actions.rs:490]: You were right, i'm actually moving it by creating an array each time! This compiles
```diff
diff --git a/src/daemon/database/actions.rs b/src/daemon/database/actions.rs
index 9b370dd..2c9a3da 100644
--- a/src/daemon/database/actions.rs
+++ b/src/daemon/database/actions.rs
@@ -1055,7 +1055,8 @@ mod test {
             db_vault_by_unvault_txid(&db_path, &spend_tx_inputs[0].previous_output.txid)
                 .unwrap()
                 .unwrap();
-        db_insert_spend(&db_path, &[db_unvault.clone()], &spend_tx).unwrap();
+        let arr = [db_unvault.clone()];
+        db_insert_spend(&db_path, &arr, &spend_tx).unwrap();
         let spend_txid = spend_tx.inner_tx().global.unsigned_tx.txid();
         assert_eq!(
             db_list_spends(&db_path).unwrap().get(&spend_txid),
@@ -1078,7 +1079,7 @@ mod test {
         // And this works with multiple unvaults too
 
         // Re-insert the previous one so we have many references to the first Unvault
-        db_insert_spend(&db_path, &[db_unvault.clone()], &spend_tx).unwrap();
+        db_insert_spend(&db_path, &arr, &spend_tx).unwrap();
```

Comment (darosior) [reply src/daemon/database/actions.rs]: Removed the comment.

File: src/daemon/control.rs [hunk 4]
```diff
@@ -1103,6 +1103,20 @@ pub fn handle_rpc_messages(
 
                 response_tx.send(Ok(()))?;
             }
+            RpcMessageIn::ListSpendTxs(response_tx) => {
+                let db_path = revaultd.read().unwrap().db_file();
+
+                let mut spend_tx_map = db_list_spends(&db_path)?;
+                let mut listspend_entries = Vec::with_capacity(spend_tx_map.len());
+                for (_, (psbt, deposit_outpoints)) in spend_tx_map.drain() {
```
Comment (danielabrozzoni) [inline src/daemon/control.rs:1289]: nit: Do you really need the `drain()` here?
```
--- a/src/daemon/control.rs
+++ b/src/daemon/control.rs
@@ -1284,9 +1284,9 @@ pub fn handle_rpc_messages(
             RpcMessageIn::ListSpendTxs(response_tx) => {
                 let db_path = revaultd.read().unwrap().db_file();
 
-                let mut spend_tx_map = db_list_spends(&db_path)?;
+                let spend_tx_map = db_list_spends(&db_path)?;
                 let mut listspend_entries = Vec::with_capacity(spend_tx_map.len());
-                for (_, (psbt, deposit_outpoints)) in spend_tx_map.drain() {
+                for (_, (psbt, deposit_outpoints)) in spend_tx_map {
                     listspend_entries.push(ListSpendEntry {
```

Comment (darosior) [reply src/daemon/control.rs:1289]: I found it somewhat more explicit, but i can change it

Comment (darosior) [reply src/daemon/control.rs:1289]: Ok went for it to remove the `mut`, thanks!

**Comment by darosior** [comment]
Made the `test_large_spends` test case sign-and-wait in parallel. Resulted in a factor 2 speedup:
```diff
diff --git a/tests/test_misc.py b/tests/test_misc.py
index cfad5ea..a9a7d64 100644
--- a/tests/test_misc.py
+++ b/tests/test_misc.py
@@ -1142,7 +1142,7 @@ def test_spends_conflicting(revault_network, bitcoind):
 # FIXME: exchange of signatures with the cosigning server gets too large too quickly
 # See https://github.com/revault/practical-revault/issues/81
 @pytest.mark.skipif(not POSTGRES_IS_SETUP, reason="Needs Postgres for servers db")
-def test_large_spends(revault_network, bitcoind):
+def test_large_spends(revault_network, bitcoind, executor):
     CSV = 2016  # 2 weeks :tm:
     revault_network.deploy(9, 4, csv=CSV)
     man = revault_network.man_wallets[0]
@@ -1150,11 +1150,23 @@ def test_large_spends(revault_network, bitcoind):
     deposits = []
     deriv_indexes = []
     total_amount = 0
+    revtx_futures = []
     for _ in range(15):
         amount = random.randint(5, 5000) / 100
         vault = revault_network.fund(amount)
-        revault_network.secure_vault(vault)
-        revault_network.activate_vault(vault)
+        revtx_futures.append(
+            (vault, executor.submit(revault_network.secure_vault, vault))
+        )
+
+    unvaulttx_futures = []
+    for (vault, fut) in revtx_futures:
+        fut.result(TIMEOUT)
+        unvaulttx_futures.append(
+            (vault, executor.submit(revault_network.activate_vault, vault))
+        )
+
+    for (vault, fut) in unvaulttx_futures:
+        fut.result(TIMEOUT)
         deposits.append(f"{vault['txid']}:{vault['vout']}")
         deriv_indexes.append(vault["derivation_index"])
         total_amount += vault["amount"]
 ```

File: src/daemon/database/schema.rs [hunk 5]
```diff
@@ -68,20 +69,47 @@ CREATE TABLE presigned_transactions (
...
+);
+
+/* This stores Spend transactions we created. A txid row is there to
+ * ease research.
+ */
+CREATE TABLE spend_transactions (
+    id INTEGER PRIMARY KEY NOT NULL,
+    psbt BLOB UNIQUE NOT NULL,
+    txid BLOB UNIQUE NOT NULL,
+    broadcast BOOLEAN NOT NULL CHECK (broadcast IN (0,1))
```
Comment (edouardparis) [inline src/daemon/database/schema.rs:102]: Maybe move to a ternary status: 0, 1, 2 (broadcasted)

Comment (darosior) [reply src/daemon/database/schema.rs:102]: Done

File: src/daemon/control.rs [hunk 6]
```diff
@@ -456,6 +543,80 @@ fn share_unvault_signatures(
...
+                .to_string(),
+        ))?;
+        if res_tx.inner_tx().inputs.len() != spend_tx.inner_tx().inputs.len() {
+            // They lied to us, no need to go further.
+            log::error!(
+                "Cosigning server sent us a bad Spend transaction: '{}', our is '{}'",
+                res_tx.as_psbt_string(),
+                spend_tx.as_psbt_string()
+            );
+            return Ok(());
```
Comment (danielabrozzoni) [inline src/daemon/control.rs:589]: Can you please explain why you're returning Ok(()) even if the cosigner server lied?

File: doc/API.md [hunk 7]
```diff
@@ -278,14 +289,73 @@ feerate.
...
+| Field          | Type   | Description                                                          |
+| -------------- | ------ | -------------------------------------------------------------------- |
+| `spend_txs`    | array  | Array of [Spend transaction resources](#spend_transaction_reources)  |
+
+##### Spend transaction resources
+
+| Field                  | Type          | Description                                                           |
+| ---------------------- | ------------- | --------------------------------------------------------------------- |
+| `deposit_outpoints`    | string array  | Array of the deposit outpoints of the vaults this transaction spends  |
+| `psbt`                 | string        | Base64-encoded Spend transaction PSBT                                 |
```
Comment (edouardparis) [inline doc/API.md:342]: Is it possible to modify `getspendtx` response in this PR, in order to have the same `Spend transaction resource` for both `listspendtxs` and `getspendtx` ?

File: src/daemon/control.rs (hunk 6 above)
Comment (darosior) [reply src/daemon/control.rs:589]: To be honest i don't think we can have decent detailed errors until we get rid of the JSONRPC thread and stuff calls in jsonrpc/api.rs

This is just going to fail the finalization later, i know it's horrible..

Comment (darosior) [reply src/daemon/control.rs:589]: i mean i can just abuse jsonrpc::Error again..

File: doc/API.md (hunk 7 above)
Comment (darosior) [reply doc/API.md:342]: Discussed in face to face and we agreed it was ugly to return something you've been input'ed

File: src/daemon/control.rs (hunk 6 above)
Comment (darosior) [reply src/daemon/control.rs:589]: Oh, actually it can not happen https://github.com/revault/revault_tx/blob/b0502d50ac20d65fbc5f4960d3aae7f7e736da69/src/transactions.rs#L480-L487

Comment (darosior) [reply src/daemon/control.rs:589]:
```diff
diff --git a/src/daemon/control.rs b/src/daemon/control.rs
index b377788..84603ba 100644
--- a/src/daemon/control.rs
+++ b/src/daemon/control.rs
@@ -579,22 +579,15 @@ fn fetch_cosigner_signatures(
                 one of these vaults!"
                 .to_string(),
         ))?;
-        if res_tx.inner_tx().inputs.len() != spend_tx.inner_tx().inputs.len() {
-            // They lied to us, no need to go further.
-            log::error!(
-                "Cosigning server sent us a bad Spend transaction: '{}', our is '{}'",
-                res_tx.as_psbt_string(),
-                spend_tx.as_psbt_string()
-            );
-            return Ok(());
-        }
 
         for (i, psbtin) in res_tx.into_psbt().inputs.into_iter().enumerate() {
             spend_tx
                 .inner_tx_mut()
                 .inputs
                 .get_mut(i)
-                .expect("Checked above")
+                .expect(
+                    "A SpendTransaction cannot have a different number of txins and PSBT inputs",
+                )
                 .partial_sigs
                 .extend(psbtin.partial_sigs);
         }
```

**Comment by darosior** [comment]
Ok, pushed a hopefully final version, thanks everyone for bearing with me and my hacks

**Comment by darosior** [comment]
Removed the concurrency too and opened https://github.com/revault/revaultd/issues/135

**Review by edouardparis — APPROVED** [review]
ACK a5ffd9c3449ee0798d4c98ad07bfae8669ce558c

File: doc/API.md [hunk 8]
```diff
@@ -16,7 +16,12 @@ Note that all addresses are bech32-encoded *version 0* native Segwit `scriptPubK
 | [`listvaults`](#listvaults)                                 | Display a paginated list of vaults                   |
 | [`revocationtxs`](#revocationtxs)                           | Give back the revocation transactions signed         |
 | [`unvaulttx`](#unvaulttx)                                   | Give back the unvault transaction signed             |
-| [`spendtx`](#spendtx)                                       | Give back the spend transaction signed               |
+| [`updatependtx`](#updatespendtx)                            | Store or update the stored Spend transaction         |
```
Comment (danielabrozzoni) [inline doc/API.md:19]: An s is missing ("update pend tx")

File: doc/API.md [hunk 9]
```diff
@@ -278,14 +289,73 @@ feerate.
...
+| `psbt`                 | string        | Base64-encoded Spend transaction PSBT                                 |
+
+
+### `setspendtx`
 
 #### Request
 
 | Field        | Type   | Description                                    |
 | ------------ | ------ | ---------------------------------------------- |
 | `spend_tx`   | string | Base64-encoded Spend transaction PSBT          |
```
Comment (danielabrozzoni) [inline doc/API.md:351]: I think `setspendtx` takes a txid?

Comment (darosior) [reply doc/API.md]: :sob:
Done

**Review by edouardparis — APPROVED** [review]
ACK bf3d941561396aba461274cc3d9e4f89f7f56cb0
